services:
  db:
    container_name: database
    image: postgres:17.5
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: paypal_clone
    volumes:
      - ./src/db/postgres:/etc/postgres/db
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: