services:
  db:
    container_name: database
    image: postgres:17.5
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: paypal_clone
    volumes:
      - ./src/db/postgres:/etc/postgres/db